services:
  web:
    
    build: .
    image: tahaalghutani/myapp-aws
    volumes:
      - .:/app   
    environment:
      - DEBUG=0
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,[::1],13.60.26.157
      - POSTGRES_DB=django_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=example
      - DB_HOST=postgres
      - DB_PORT=5432

    depends_on: 
      - postgres
      - redis


  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      
    
  # mongo-express:

  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  #     ME_CONFIG_BASICAUTH_USERNAME: root
  #     ME_CONFIG_BASICAUTH_PASSWORD: example
  #   depends_on:
  #     - mongo
  redis:
    image: redis
  nginx:
  
    image: nginx:stable-alpine
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
    depends_on:
      - web
    

volumes:

  mongo_data:
  postgresql_data:
